# Path to the training split parquet or csv file
train_split: "data/splits/donate/train.parquet"

# Path to validation data (optional for now)
validation_split: "data/splits/donate/val.parquet"

# Embedding directories
user_emb_dir: "embeddings/user/MiniLM_40epoch/item_sentence"
streamer_emb_dir: "embeddings/streamer/MiniLM_40epoch/item_sentence"

# Training hyperparameters
epochs: 100
batch_size: 512
lr: 1.0e-4
patience: 5

# Output directory
out_dir: "ranker/checkpoints/mlp/default"
