# Path to the training split parquet or csv file
train_split: "data/splits/donate/train.parquet"

# Path to validation data (optional for now)
val_split: "data/splits/donate/val.parquet"

# Path to test data (optional for now)
test_split: "data/splits/donate/test.parquet"

# Path to the retrieval results file
retrieval_dir: "results/retrieval/MiniLM_40epoch/item_sentence"

user_log_path: "data/splits/donate/interactions_train.parquet"

# Embedding directories
user_emb_dir: "embeddings/user/MiniLM_40epoch/item_sentence"
streamer_emb_dir: "embeddings/streamer/MiniLM_40epoch/item_sentence"

# model configuration
model: "contextual" 
d_model: 256

# Training hyperparameters
loss_type: "pairwise"  # Options: "pairwise", "pointwise"
epochs: 100
batch_size: 512
lr: 1.0e-5
patience: 5
val_freq: 1

# Output directory
out_dir: "src/ranker/torch/checkpoints/contextual/default"
